
spring:
    config:
        name: spring-cloud-config
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/exercisecode/spring-config-repo
                        

server:
    port: 30000
    
management:
    context-path: /admin    
    
    
---
spring:
    profiles: cloud    